import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Duende",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/iconDuende_2.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <img className="absolute right-0 bottom-0 w-20 h-19" src="/iconDuende_2.png" alt="logo" />

        <header className="flex justify-center items-center pt-10">
          <div className="flex justify-between items-center lg:w-[840px] md:w-[500px]">
            <div className="relative flex items-center h-7">
              <img className="absolute left-2 w-4 h-4 brightness-10 invert-80" src="/loupe.png" alt="" />

              <input className="pl-8 pr-2 py-2 w-100 rounded-xl text-white bg-gray-700/30 border-gray-600 border-1" type="text" placeholder="Поиск" />
            </div>

            <Link href='/logIn' className="text-white font-semibold bg-blue-600
                       hover:bg-blue-700 transition-colors duration-300 shadow-md
                       focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 ml-15 px-15 py-2 rounded-sm">Вход</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
