import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Header from "@/components/Header";
import "./globals.css";
import ClientVisibility from "./clientComponents/ClientVisibility";
// import ClientVisibility from "./clientComponents/ClientVisibility";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Duende",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/iconDuende_2.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientVisibility>
          <img className="absolute right-0 bottom-0 w-20 h-19 hide-log" src="/iconDuende_2.png" alt="logo" />
        </ClientVisibility>

				<ReactQueryProvider>
        	{children}
				</ReactQueryProvider>
      </body>
    </html>
  );
}
